### ISSUE TITLE
Pineap doesn't work

### ISSUE THREAD

**Issue by Alsllsls** [xchwarze/wifi-pineapple-cloner-builds#1]
i use Gl-ar300m16-ext I'm using pineapple web I'm going to get into the recon,  scanning from recon, but it's giving  error

**Comment by xchwarze** [comment]
Your device only have 1 wifi. 
So you need to add a second one from usb, check "Recomended setup" in docs
you can also explore the rest of the original repo issues

**Comment by patatessss121aq** [comment]
I don't quite understand, where are the docs, how do I install which file from the usb, sorry I'm bothering you a little bit. The person who wrote it is my side account
