### ISSUE TITLE
Your device only have 1 wifi.

### ISSUE THREAD

**Issue by patatessss121aq** [xchwarze/wifi-pineapple-cloner-builds#2]
Your device only have 1 wifi. 
So you need to add a second one from usb, check "Recomended setup" in docs
you can also explore the rest of the original repo issues

_Originally posted by @xchwarze in https://github.com/xchwarze/wifi-pineapple-cloner-builds/issues/1#issuecomment-1234333323_
****

I don't quite understand, where are the docs, how do I install which file from the usb, sorry I'm bothering you a little bit. The person who wrote it is my side account

**Comment by xchwarze** [comment]
The docs are located in the sources repo https://github.com/xchwarze/wifi-pineapple-cloner
```
Recomended setup

    [GL-AR150](https://www.gl-inet.com/products/gl-ar150/) or [TPLink Archer C7](https://www.tp-link.com/en/home-networking/wifi-router/archer-c7/)
    USB 2.0 [2 ports hub](https://www.ebay.com/itm/144520475350)
    Generic [RT5370 WIFI adapter](https://www.ebay.com/itm/284904442887) you're really going to need this for nano builds
    Please support Hak5 work and buy the original hardware
```

yoy can read more in [AR150-WiFiPineapple](https://github.com/xchwarze/AR150-WiFiPineapple/) issues like this https://github.com/xchwarze/AR150-WiFiPineapple/issues/26
