### ISSUE TITLE
[Archer C7 v2] Install via Web Interface?

### ISSUE THREAD

**Issue by rdtm443** [xchwarze/wifi-pineapple-cloner-builds#3]
Hey there :)

First of all, your work is highly appreciated, thanks! Cool stuff.

Was just trying to figure out how to install the Pineapple Firmware on my Archer C7 v2. 

Here is what I understand, coming from pure stock firmware:

I download the latest prebuilt sysupgrade.bin from this repo and flash it via the web interface. Then format a usb stick from within the pineapple GUI, connect it to the internet and reboot?

Thanks in advance :)

Best regards

**Comment by xchwarze** [comment]
first install OpenWrt 19.x
