### ISSUE TITLE
Prebuilt image for C7 v2: root password?

### ISSUE THREAD

**Issue by rdtm443** [xchwarze/wifi-pineapple-cloner-builds#4]
Hello there !

Managed to install your prebuilt wifi pineapple image on my archer c7 v2, but getting stuck at boot. I've read your remark concerning this issue, but can't login via ssh with root and root: wrong password.

I did not set a custom password, was not asked to do so.

Thanks a lot!

Best,

rdtm443

**Comment by xchwarze** [comment]
https://github.com/xchwarze/wifi-pineapple-cloner/blob/master/tools/fs-patcher.sh#L127
anyway I understand that the only way that happens is that you don't use the -n when installing

**Comment by rdtm443** [comment]
Thanks. How could this possibly be fixed? I have access via serial console...

**Comment by xchwarze** [comment]
If you did not install indicating to delete everything the only thing left are the recovery methods.
I don't remember which ones were from the C7.
That is why in the documentation it is explained that it is installed like this "sysupgrade -n -F /tmp/archer-c7-v5-tetra-sysupgrade.bin"
I guess you installed it from Luci and didn't hit check to use -n

**Comment by rdtm443** [comment]
> If you did not install indicating to delete everything the only thing left are the recovery methods.
> I don't remember which ones were from the C7.
> That is why in the documentation it is explained that it is installed like this "sysupgrade -n -F /tmp/archer-c7-v5-tetra-sysupgrade.bin"
> I guess you installed it from Luci and didn't hit check to use -n

Yea true, was uploading the fw via web interface - my bad. I did now a complete reset, but getting stuck at "Secure setup: Quickly press reset button...". Nothing happens whether i push the reset button quickly or holding it longer. Any fix for that? 

Thanks :)
