### ISSUE TITLE
[Archer C7 V2] Stuck at secure setup screen

### ISSUE THREAD

**Issue by rdtm443** [xchwarze/wifi-pineapple-cloner-builds#5]
Hello

I completed the setup exactly as described and managed to connect to the wifi pineapple. The problem i am facing is, that i got stuck at the secure setup welcome screen, where i am supposed to press the reset button either quickly (no wifi) or long (wifi). None of the methods work, it is just stuck.

Any workaround? I also found that at this step ssh is somehow not active (can't connect directly over [w]lan). The only way to get to access to the base system is via serial connection. Maybe there is a way to disable secure setup...

Thanks in advance !

Best,

rdtm443

**Comment by xchwarze** [comment]
I'm doing another batch of builds based on this update so you don't have any problems starting Termidor.
https://github.com/xchwarze/wifi-pineapple-cloner/commit/b51c8ff78724794e6cb6dafcb1c64a4af3c3e5fc
In a few minutes it will be available to download.

Regarding the problem you are having, it is strange, perhaps your router has the name of the button changed and that is why it does not start.

The button runs this script:
https://github.com/xchwarze/wifi-pineapple-cloner/blob/c5edea6cf2c5e76a83c863960a6d689d0cd0e534/lists/nano.filelist#L31

`#!/bin/sh
. /lib/functions.sh

device="NANO"
if [[ $(cat /proc/cpuinfo | grep 'machine' | awk {'print $1'}) == "NANO" ]]; then
    device="NANO"
elif [[ $(cat /proc/cpuinfo | grep 'machine' | awk {'print $1'}) == "TETRA" ]]; then
    device="TETRA"
fi

[ "${ACTION}" = "pressed" ] && {
    /usr/bin/pineapple/blink &
}

[ "${ACTION}" = "released" ] || exit 0

killall blink
/sbin/led reset

if [ -f "/etc/pineapple/setupRequired" ]; then
    if [ -f /etc/pineapple/init ]; then
        exit
    fi

    if [ ! -f /tmp/button_setup ]; then
        if [ "$SEEN" -lt 2 ]; then
            logger "First Setup: Disable WiFi"
            wifi down
            ifconfig wlan0 down && ifconfig wlan0-1 down
            /sbin/led blue on
        else
            logger "First Setup: Keep WiFi On"
        fi
        touch /tmp/button_setup
    fi
    exit
fi

if [ "$SEEN" -lt 6 ]; then
    bash /etc/pineapple/button_script
else
    echo "FACTORY RESET" > /dev/console
    jffs2reset -y && reboot &
fi

return 0
`

If I remember correctly running this would do the trick `touch /tmp/button_setup`

**Comment by rdtm443** [comment]
Thanks a lot, this did the trick (via UART/serial connection):

touch /tmp/button_setup

Once again, thank you so much for bringin the WiFi Pineapple to the Archer C7 V2 :)

Best,

rdtm443

**Comment by xchwarze** [comment]
Could you install the latest version and share the debug log?
The log is generated in Help using the `Download Debug File` option.
I would like to understand why the reset button does not work for you

**Comment by rdtm443** [comment]
> Could you install the latest version and share the debug log?
> The log is generated in Help using the `Download Debug File` option.
> I would like to understand why the reset button does not work for you

Latest release (about 10days old) is up and running.

Tried to get the log, but states "invalid download token"...

**Comment by xchwarze** [comment]
@rdtm443 run via ssh this
```
LOG=/tmp/debug.log.tmp

touch $LOG
echo "Retrieving /proc/cpuinfo"
echo "============CPUINFO========" > $LOG
cat /proc/cpuinfo >> $LOG
echo "Retrieving firmware version"
echo -n "Firmware Version: " >> $LOG && cat /etc/pineapple/pineapple_version >> $LOG
echo "Retrieving lsusb output"
echo "=============LSUSB=========" >> $LOG
lsusb >> $LOG
echo "Retrieving dmesg log"
echo "============DMESG==========" >> $LOG
dmesg >> $LOG
echo "Retrieving syslog"
echo "============LOGREAD========" >> $LOG
logread >> $LOG
```

**Comment by rdtm443** [comment]
Will check on that this weekend, if I find time. Super busy at the moment...
