### ISSUE TITLE
WNDR4300 v1 NAND question

### ISSUE THREAD

**Issue by Riccardo451** [xchwarze/wifi-pineapple-cloner-builds#6]
Good Morning,

I have a Netgear WNDR4300 v1 with NAND flash (stock firmware on it for now).
However I saw that there is a package pre compiled in this directory to install wifi pineapple that is using the flavor: universal.
For this reason I've searched for the correct 19.07.07 firmware to install on https://downloads.openwrt.org/releases/19.07.7/targets/ath79/generic/
but WNDR4300 v1 is not present (is not present neither in NAND branch because was released in a later revision.

Before risking to brick my router, could someone give me some tips on which firmware is better to use? Do I have to compile a 19.07.07 NAND firmware and also compile the wifi pineapple cloner for NAND?

Thank you so much

Riccardo

**Comment by xchwarze** [comment]
Hi!
The correct folder is: https://downloads.openwrt.org/releases/19.07.7/targets/ar71xx/nand/
