### ISSUE TITLE
Update from WPC 1.0 to 2.0 from Pineapple Web Interface?

### ISSUE THREAD

**Issue by rdtm443** [xchwarze/wifi-pineapple-cloner-builds#7]
Hello

Just saw that you released v2.0 a few days ago. Cool !

Is it possible to upgrade directly from pineapple web interface from wpc 1.0 to wpc 2.0?

Thanks !

**Comment by rdtm443** [comment]
> The intention of the tagged versions is to be able to rollback with what is in master (which in this case is v3)
> 
> To update you can use the "manual upgrade" option of the panel and put the direct download url of the firmware. For example for `gl-ar750s` it would be `https://github.com/xchwarze/wifi-pineapple-cloner-builds/raw/main/releases/gl-ar750s-universal-sysupgrade.bin`

Found some time today to test it, unfortunately it got stuck at whatever:

![image](https://user-images.githubusercontent.com/25002690/198826881-2711704e-6baa-48d4-b529-c9a98bef1bb3.png)

Really good work, once more, thanks a lot!!!

**Comment by xchwarze** [comment]
The url you put is for viewing and not for downloading. In Github click on "Download" and copy the url.
It has to generate one for you with the word "raw" in the url.

**Comment by rdtm443** [comment]
> The url you put is for viewing and not for downloading. In Github click on "Download" and copy the url.
> It has to generate one for you with the word "raw" in the url.

Thanks for the info and your patience :)
